version: "3.8"

services:
  neo4j:
    container_name: "neo4j-rag"
    build: ./neo4j
    ports:
      # "<(laptop/desktop)host_port>:<container_port>"
      - "7474:7474"
      - "7687:7687"
    environment:
      # <username>/<password>
      NEO4J_AUTH: "neo4j/p@ssw0rd"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      # Create new database
      NEO4J_initial_dbms_default__database: "neo4j-rag"
      # NEO4J_dbms_memory_heap_maxSize: "4G"
      # NEO4J_dbms_memory_heap_initialSize: "512M"
    volumes:
      - ./data:/data
